"""made changes

Revision ID: 284ba22d6815
Revises: 3dc1d64d22f7
Create Date: 2023-09-05 14:10:56.658600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '284ba22d6815'
down_revision: Union[str, None] = '3dc1d64d22f7'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('dislike_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('last_login_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_request_date', sa.DateTime(), nullable=True))
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_online', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_request_date')
    op.drop_column('users', 'last_login_date')
    op.drop_table('dislikes')
    # ### end Alembic commands ###
