"""made changes

Revision ID: 2a1ba687cb36
Revises: 50be770ecf0d
Create Date: 2023-09-05 13:00:29.058110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1ba687cb36'
down_revision: Union[str, None] = '50be770ecf0d'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('like_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'like_date')
    # ### end Alembic commands ###
