"""made changes

Revision ID: 3dc1d64d22f7
Revises: 4f269f7dae8c
Create Date: 2023-09-05 13:55:14.783237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc1d64d22f7'
down_revision: Union[str, None] = '4f269f7dae8c'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_online', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_online')
    # ### end Alembic commands ###
