"""made changes

Revision ID: 4f269f7dae8c
Revises: 2a1ba687cb36
Create Date: 2023-09-05 13:10:32.367166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f269f7dae8c'
down_revision: Union[str, None] = '2a1ba687cb36'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('like_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('posts', 'like_date')
    op.drop_column('posts', 'likes')
    op.drop_column('posts', 'dislikes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('like_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('likes')
    # ### end Alembic commands ###
